name: Deploy Spring Boot getfinalconsumerbill to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Build Spring Boot JAR
        working-directory: ./finalconsumer/getallfinalconsumerbill
        run: ./mvnw clean package -DskipTests
    
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}
    
      - name: Copy files to VPS
        run: |
          scp -o StrictHostKeyChecking=no \
          ./finalconsumer/getfinalconsumerbill/target/*.jar \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/bill/getBill/getfinalconsumerbill.jar
    
          scp -o StrictHostKeyChecking=no \
          ./finalconsumer/getfinalconsumerbill/Dockerfile \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/bill/getBill/Dockerfile
    
      - name: Deploy Docker on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/${{ secrets.VPS_USER }}/bill/getBill
            docker stop getfinalconsumerbill || true
            docker rm getfinalconsumerbill || true
            docker build -t getfinalconsumerbill .
            docker run -d --name getfinalconsumerbill \
              -p 8080:8080 \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              getfinalconsumerbill
          EOF
